import type { Metadata } from "next";
import { Unbounded, Albert_Sans, Murecho } from "next/font/google";
import "./globals.css";

const unbounded = Unbounded({
	variable: "--font-unbounded",
	subsets: ["latin"],
});

const albertsans = Albert_Sans({
	variable: "--font-albert-sans",
	subsets: ["latin"],
});

const murecho = Murecho({
	variable: "--font-murecho",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${unbounded.variable} ${albertsans.variable}${murecho.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
