import type { Metadata } from "next";
import { Unbounded, Albert_Sans, Murecho } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";

const unbounded = Unbounded({
	variable: "--font-unbounded",
	subsets: ["latin"],
});

const albertsans = Albert_Sans({
	variable: "--font-albert-sans",
	subsets: ["latin"],
});

const murecho = Murecho({
	variable: "--font-murecho",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div
					className={`${unbounded.variable} ${albertsans.variable}${murecho.variable} flex h-screen bg-[#0e0e12] text-[#d4d4d8] overflow-hidden`}
				>
					<Sidebar />
					<div className="flex-1 flex flex-col overflow-hidden">{children}</div>
				</div>
			</body>
		</html>
	);
}
